(function(){
'use strict';
const KEY='garageGurusWorkshopInventoryV1', INV_KEY='wai0991Invoices';
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const write=db=>{localStorage.setItem(KEY,JSON.stringify(db));window.dispatchEvent(new CustomEvent('garage-inventory-updated',{detail:db}))};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const money=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(Number(n)||0);
const uid=()=>`stk_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;
const db=()=>{const x=read(KEY,{parts:[],tyres:[],oil:[],movements:[]});x.parts=x.parts||[];x.tyres=x.tyres||[];x.oil=x.oil||[];x.movements=x.movements||[];return x};
const cfg={
 part:{bucket:'parts',host:'partsStockHost',title:'Parts Stock',subtitle:'Load workshop parts, search by description or exact part number, and add stocked items directly to an invoice. Stock reduces immediately when used.',qtyKey:'qty',unit:'items'},
 tyre:{bucket:'tyres',host:'tyreStockHost',title:'Tyre Stock',subtitle:'Search your tyre inventory by size, brand or pattern and allocate tyres directly to customer invoices.',qtyKey:'qty',unit:'tyres'},
 oil:{bucket:'oil',host:'oilStockHost',title:'Oil Stock',subtitle:'Track litres by oil grade/specification and add the exact quantity used to an invoice. Oil stock reduces immediately.',qtyKey:'litres',unit:'litres'}
};
function itemSearchText(type,x){return type==='part'?[x.description,x.partNumber,x.category,x.supplier,x.location].join(' '):type==='tyre'?[x.size,x.brand,x.pattern,x.loadSpeed,x.location].join(' '):[x.grade,x.brand,x.spec,x.location].join(' ')}
function form(type){if(type==='part')return `<div class="inventory-form"><label>Description<input id="inv-description" placeholder="e.g. Air filter"></label><label>Part number<input id="inv-partNumber" placeholder="Exact part number"></label><label>Category<input id="inv-category" placeholder="Filters, brakes..."></label><label>Supplier<input id="inv-supplier"></label><label>Quantity<input id="inv-qty" type="number" min="0" step="1"></label><label>Cost ex VAT<input id="inv-cost" type="number" min="0" step="0.01"></label><label>Sell ex VAT<input id="inv-sell" type="number" min="0" step="0.01"></label><label>Minimum stock<input id="inv-minStock" type="number" min="0" step="1"></label><label>Location<input id="inv-location" placeholder="Shelf / bin"></label></div>`;
if(type==='tyre')return `<div class="inventory-form"><label>Tyre size<input id="inv-size" placeholder="e.g. 225/45 R17"></label><label>Brand<input id="inv-brand" placeholder="Michelin"></label><label>Pattern<input id="inv-pattern"></label><label>Load / speed<input id="inv-loadSpeed" placeholder="94Y"></label><label>Quantity<input id="inv-qty" type="number" min="0" step="1"></label><label>Cost ex VAT<input id="inv-cost" type="number" min="0" step="0.01"></label><label>Sell ex VAT<input id="inv-sell" type="number" min="0" step="0.01"></label><label>Minimum stock<input id="inv-minStock" type="number" min="0" step="1"></label><label>Location<input id="inv-location"></label></div>`;
return `<div class="inventory-form"><label>Oil grade<input id="inv-grade" placeholder="e.g. 5W30"></label><label>Brand<input id="inv-brand"></label><label>Specification<input id="inv-spec" placeholder="e.g. VW 504 00 / 507 00"></label><label>Litres in stock<input id="inv-litres" type="number" min="0" step="0.1"></label><label>Cost £ / litre<input id="inv-costPerLitre" type="number" min="0" step="0.01"></label><label>Sell £ / litre<input id="inv-sellPerLitre" type="number" min="0" step="0.01"></label><label>Minimum litres<input id="inv-minStock" type="number" min="0" step="0.1"></label><label>Location<input id="inv-location"></label></div>`}
function addItem(type){const d=db(),c=cfg[type],g=id=>document.getElementById('inv-'+id)?.value||'';let item={id:uid(),createdAt:new Date().toISOString(),minStock:Number(g('minStock'))||0,location:g('location')};if(type==='part')Object.assign(item,{description:g('description').trim(),partNumber:g('partNumber').trim().toUpperCase(),category:g('category').trim(),supplier:g('supplier').trim(),qty:Number(g('qty'))||0,cost:Number(g('cost'))||0,sell:Number(g('sell'))||0});if(type==='tyre')Object.assign(item,{size:g('size').trim().toUpperCase(),brand:g('brand').trim(),pattern:g('pattern').trim(),loadSpeed:g('loadSpeed').trim().toUpperCase(),qty:Number(g('qty'))||0,cost:Number(g('cost'))||0,sell:Number(g('sell'))||0});if(type==='oil')Object.assign(item,{grade:g('grade').trim().toUpperCase(),brand:g('brand').trim(),spec:g('spec').trim(),litres:Number(g('litres'))||0,costPerLitre:Number(g('costPerLitre'))||0,sellPerLitre:Number(g('sellPerLitre'))||0});if(type==='part'&&!item.description&&!item.partNumber)return alert('Enter a part description or part number.');if(type==='tyre'&&!item.size)return alert('Enter the tyre size.');if(type==='oil'&&!item.grade)return alert('Enter the oil grade.');d[c.bucket].unshift(item);d.movements.unshift({id:uid(),at:new Date().toISOString(),action:'Stock item created',inventoryId:item.id,type,qty:Number(item[c.qtyKey])||0});write(d);render(type)}
function kpis(type,items){const q=items.reduce((a,x)=>a+(Number(x[cfg[type].qtyKey])||0),0),low=items.filter(x=>(Number(x[cfg[type].qtyKey])||0)<=Number(x.minStock||0)).length;const value=items.reduce((a,x)=>a+(Number(x[cfg[type].qtyKey])||0)*Number(type==='oil'?x.costPerLitre:x.cost||0),0);return `<div class="inventory-kpis"><div class="inventory-kpi"><span>Stock lines</span><strong>${items.length}</strong></div><div class="inventory-kpi"><span>${cfg[type].unit} in stock</span><strong>${Math.round(q*10)/10}</strong></div><div class="inventory-kpi"><span>Low stock</span><strong>${low}</strong></div><div class="inventory-kpi"><span>Stock cost value</span><strong>${money(value)}</strong></div></div>`}
function rows(type,items){if(!items.length)return `<tr><td colspan="9" class="inventory-empty">No stock loaded yet.</td></tr>`;return items.map(x=>{const qty=Number(x[cfg[type].qtyKey])||0,low=qty<=Number(x.minStock||0),main=type==='part'?x.description:type==='tyre'?`${x.brand||''} ${x.pattern||''}`.trim():`${x.brand||''} ${x.grade||''}`.trim(),ref=type==='part'?x.partNumber:type==='tyre'?x.size:x.spec,cost=Number(type==='oil'?x.costPerLitre:x.cost)||0,sell=Number(type==='oil'?x.sellPerLitre:x.sell)||0;return `<tr class="${low?'low-stock':''}" data-stock-row="${x.id}"><td><strong>${esc(main||'—')}</strong><br><small>${esc(ref||'')}</small></td><td>${type==='part'?esc(x.category||'—'):type==='tyre'?esc(x.loadSpeed||'—'):esc(x.spec||'—')}</td><td><span class="stock-badge ${low?'low':''}">${qty} ${type==='oil'?'L':''}</span></td><td>${money(cost)}</td><td>${money(sell)}</td><td>${esc(x.location||'—')}</td><td><div class="inventory-actions"><button class="inventory-btn secondary" data-adjust="${x.id}">Adjust</button><button class="inventory-btn primary" data-add-invoice="${x.id}">Add to Invoice</button><button class="inventory-btn danger" data-delete="${x.id}">Delete</button></div><div id="invoice-panel-${x.id}"></div></td></tr>`}).join('')}
function tableHead(type){const second=type==='part'?'Category':type==='tyre'?'Load / speed':'Specification';return `<thead><tr><th>${type==='part'?'Part / Part number':type==='tyre'?'Tyre / Size':'Oil / Grade'}</th><th>${second}</th><th>In stock</th><th>Cost</th><th>Sell</th><th>Location</th><th>Actions</th></tr></thead>`}
function render(type){const c=cfg[type],host=document.getElementById(c.host);if(!host)return;const d=db(),all=d[c.bucket],q=(host.dataset.query||'').toLowerCase(),items=all.filter(x=>itemSearchText(type,x).toLowerCase().includes(q));host.innerHTML=`<div class="inventory-shell"><section class="inventory-hero"><div><span class="inventory-eyebrow">Garage Gurus Workshop · Live Inventory</span><h2>${c.title}</h2><p>${c.subtitle}</p></div><button class="inventory-btn primary" id="newStock-${type}">+ Add Stock Item</button></section>${kpis(type,all)}<section class="inventory-card"><div class="inventory-toolbar"><input id="stockSearch-${type}" value="${esc(host.dataset.query||'')}" placeholder="${type==='part'?'Search air filter, description, part number, supplier...':type==='tyre'?'Search 225/45 R17, brand or pattern...':'Search 5W30, 0W20, brand or specification...'}"><button class="inventory-btn secondary" id="clearSearch-${type}">Clear</button></div><div id="stockForm-${type}" hidden>${form(type)}<div style="margin-top:12px"><button class="inventory-btn primary" id="saveStock-${type}">Save to Stock</button></div></div><div class="inventory-table-wrap"><table class="inventory-table">${tableHead(type)}<tbody>${rows(type,items)}</tbody></table></div></section></div>`;bind(type)}
function bind(type){const host=document.getElementById(cfg[type].host),search=document.getElementById('stockSearch-'+type);search.oninput=()=>{host.dataset.query=search.value;render(type)};document.getElementById('clearSearch-'+type).onclick=()=>{host.dataset.query='';render(type)};document.getElementById('newStock-'+type).onclick=()=>{const f=document.getElementById('stockForm-'+type);f.hidden=!f.hidden};document.getElementById('saveStock-'+type)?.addEventListener('click',()=>addItem(type));host.querySelectorAll('[data-adjust]').forEach(b=>b.onclick=()=>adjust(type,b.dataset.adjust));host.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(type,b.dataset.delete));host.querySelectorAll('[data-add-invoice]').forEach(b=>b.onclick=()=>invoicePanel(type,b.dataset.addInvoice))}
function adjust(type,id){const d=db(),x=d[cfg[type].bucket].find(i=>i.id===id);if(!x)return;const key=cfg[type].qtyKey,current=Number(x[key])||0,val=prompt(`Current stock: ${current}. Enter the NEW stock level:`,current);if(val===null)return;const n=Number(val);if(!Number.isFinite(n)||n<0)return alert('Enter a valid stock level.');x[key]=n;d.movements.unshift({id:uid(),at:new Date().toISOString(),action:'Manual stock adjustment',inventoryId:id,type,qty:n-current});write(d);render(type)}
function remove(type,id){const d=db(),x=d[cfg[type].bucket].find(i=>i.id===id);if(!x||!confirm('Delete this stock item?'))return;d[cfg[type].bucket]=d[cfg[type].bucket].filter(i=>i.id!==id);write(d);render(type)}
function invoicePanel(type,id){const d=db(),x=d[cfg[type].bucket].find(i=>i.id===id),panel=document.getElementById('invoice-panel-'+id);if(!x||!panel)return;const invoices=(window.WAI099FinanceBridge?.getInvoices?.()||read(INV_KEY,[])).filter(i=>i.status==='Estimate');const targetInvoiceId=sessionStorage.getItem('garageGurusInventoryTargetInvoice')||'';if(!invoices.length){panel.innerHTML='<div class="inventory-invoice-panel">No open estimates. Create/open an estimate in Finance Centre first.</div>';return}panel.innerHTML=`<div class="inventory-invoice-panel"><strong>Add stock to estimate</strong><div class="inventory-invoice-grid"><select data-invoice-select>${invoices.map(i=>`<option value="${i.id}" ${i.id===targetInvoiceId?'selected':''}>${esc(i.number)} · ${esc(i.registration||'No reg')} · ${esc(i.customer||'No customer')}</option>`).join('')}</select><input data-invoice-qty type="number" min="${type==='oil'?'0.1':'1'}" step="${type==='oil'?'0.1':'1'}" value="${type==='oil'?'1':'1'}"><button class="inventory-btn success" data-confirm-stock>Add & Deduct Stock</button></div><div class="inventory-history">The quantity is deducted from live stock immediately when it is added to the invoice. Removing the line or deleting the estimate returns it to stock.</div></div>`;panel.querySelector('[data-confirm-stock]').onclick=()=>{const invoiceId=panel.querySelector('[data-invoice-select]').value,qty=Number(panel.querySelector('[data-invoice-qty]').value)||0,available=Number(x[cfg[type].qtyKey])||0;if(qty<=0)return alert('Enter a quantity.');if(qty>available)return alert(`Only ${available} ${cfg[type].unit} are currently in stock.`);const r=window.WAI099FinanceBridge?.addInventoryLineToInvoice?.(invoiceId,x,type,qty);if(!r?.ok)return alert(r?.message||'Could not add stock to invoice.');alert(`Added to ${r.invoiceNumber} and deducted from stock now. Remaining stock: ${Number(r.remaining||0)} ${cfg[type].unit}.`);panel.innerHTML='';if(sessionStorage.getItem('garageGurusInventoryReturnToInvoice')==='1'){sessionStorage.removeItem('garageGurusInventoryReturnToInvoice');sessionStorage.removeItem('garageGurusInventoryTargetInvoice');window.WAI099FinanceBridge?.openInvoice?.(invoiceId);}}}
function init(){Object.keys(cfg).forEach(render)}
document.addEventListener('DOMContentLoaded',init);window.addEventListener('garage-inventory-updated',()=>Object.keys(cfg).forEach(render));window.GarageGurusInventory={render,db};
})();
