(function(){
'use strict';
const META_KEY='workshopAIMediaCentreV1';
const DB_NAME='WorkshopAIMediaDB';
const STORE='files';
let records=loadMeta(), activeSendId=null, objectUrls=new Map();
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const normReg=s=>String(s||'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const displayReg=s=>{const r=normReg(s);return r.length>4?r.slice(0,-3)+' '+r.slice(-3):r};
function loadMeta(){try{const x=JSON.parse(localStorage.getItem(META_KEY)||'[]');return Array.isArray(x)?x:[]}catch(_){return[]}}
function saveMeta(){localStorage.setItem(META_KEY,JSON.stringify(records));}
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE)};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function putBlob(id,blob){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(blob,id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function getBlob(id){const db=await openDB();return new Promise((resolve,reject)=>{const req=db.transaction(STORE,'readonly').objectStore(STORE).get(id);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error)})}
async function deleteBlob(id){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
function crmCustomers(){try{return JSON.parse(localStorage.getItem('wai096_crm')||'{}').customers||[]}catch(_){return[]}}
function customerName(c){return [c.title,c.firstName,c.surname].filter(Boolean).join(' ')||c.company||'Unnamed customer'}
function populateCustomers(){const select=$('mediaCustomer');if(!select)return;const current=select.value;select.innerHTML='<option value="">Select customer (optional)</option>'+crmCustomers().map(c=>`<option value="${esc(c.id)}">${esc(customerName(c))}</option>`).join('');select.value=current;}
function selectedCustomer(){return crmCustomers().find(c=>c.id===$('mediaCustomer')?.value)}
function customerVehicleReg(c){if(!c)return'';const regs=(c.vehicles||[]).map(v=>displayReg(v.registration)).filter(Boolean);return regs.length===1?regs[0]:''}
function resetForm(){['mediaReg','mediaPhone','mediaEmail','mediaTitle','mediaNotes'].forEach(id=>{if($(id))$(id).value=''});if($('mediaCustomer'))$('mediaCustomer').value='';if($('mediaFile'))$('mediaFile').value=''}
function openAdd(){populateCustomers();resetForm();$('mediaModal')?.classList.remove('hidden');}
function closeAdd(){$('mediaModal')?.classList.add('hidden');}
function humanSize(n){if(!n)return'0 B';if(n<1024*1024)return Math.round(n/1024)+' KB';return (n/1024/1024).toFixed(1)+' MB'}
function formatDate(v){return new Date(v).toLocaleString('en-GB',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})}
async function saveRecord(){const file=$('mediaFile')?.files?.[0];const reg=displayReg($('mediaReg')?.value);if(!reg){alert('Please enter a vehicle registration.');return}if(!file){alert('Please choose or record a video or photo.');return}const id='MED-'+Date.now().toString(36).toUpperCase()+Math.random().toString(36).slice(2,5).toUpperCase();const customer=selectedCustomer();const rec={id,createdAt:new Date().toISOString(),reg:normReg(reg),customerId:customer?.id||'',customerName:customer?customerName(customer):'',phone:$('mediaPhone').value.trim(),email:$('mediaEmail').value.trim(),title:$('mediaTitle').value.trim()||(/video/i.test(file.type)?'Vehicle video':'Vehicle photo'),notes:$('mediaNotes').value.trim(),fileName:file.name||'vehicle-media',mime:file.type||'application/octet-stream',size:file.size||0,sendLog:[]};try{await putBlob(id,file)}catch(e){console.error(e);alert('The media could not be saved on this device.');return}records.unshift(rec);saveMeta();closeAdd();render();}
async function getUrl(rec){if(objectUrls.has(rec.id))return objectUrls.get(rec.id);const blob=await getBlob(rec.id);if(!blob)return'';const url=URL.createObjectURL(blob);objectUrls.set(rec.id,url);return url}
function previewHtml(rec){const isVideo=/^video\//i.test(rec.mime);return `<div class="media-preview" data-preview-id="${rec.id}"><div class="media-preview-placeholder">${isVideo?'▶':'▧'}</div><span class="media-type-badge">${isVideo?'Video':'Photo'}</span></div>`}
async function hydratePreviews(){for(const rec of visibleRecords()){const host=document.querySelector(`[data-preview-id="${CSS.escape(rec.id)}"]`);if(!host)continue;const url=await getUrl(rec);if(!url)continue;if(/^video\//i.test(rec.mime))host.innerHTML=`<video src="${url}" controls preload="metadata"></video><span class="media-type-badge">Video</span>`;else host.innerHTML=`<img src="${url}" alt="${esc(rec.title)}"><span class="media-type-badge">Photo</span>`}}
function visibleRecords(){const q=String($('mediaSearch')?.value||'').toLowerCase(),type=$('mediaTypeFilter')?.value||'all',status=$('mediaStatusFilter')?.value||'all';return records.filter(r=>{const isVideo=/^video\//i.test(r.mime),sent=(r.sendLog||[]).length>0;if(type==='video'&&!isVideo)return false;if(type==='image'&&isVideo)return false;if(status==='sent'&&!sent)return false;if(status==='unsent'&&sent)return false;if(q&&!`${r.reg} ${r.customerName} ${r.title} ${r.notes}`.toLowerCase().includes(q))return false;return true})}
function render(){const list=$('mediaLibrary'),empty=$('mediaEmpty');if(!list)return;const rows=visibleRecords();$('mediaCount').textContent=records.length;$('mediaVideoCount').textContent=records.filter(r=>/^video\//i.test(r.mime)).length;$('mediaSentCount').textContent=records.filter(r=>(r.sendLog||[]).length).length;$('mediaVehicleCount').textContent=new Set(records.map(r=>normReg(r.reg)).filter(Boolean)).size;empty?.classList.toggle('hidden',rows.length>0);list.innerHTML=rows.map(r=>`<article class="media-card">${previewHtml(r)}<div class="media-card-body"><div class="media-card-title"><h3>${esc(r.title)}</h3><span class="media-reg">${esc(displayReg(r.reg))}</span></div><div class="media-card-meta"><span><strong>${esc(r.customerName||'No customer linked')}</strong></span><span>${esc(r.fileName)} · ${humanSize(r.size)}</span><span>Saved ${formatDate(r.createdAt)}</span>${(r.sendLog||[]).length?`<span class="media-sent-badge">Shared ${(r.sendLog||[]).length} time${r.sendLog.length===1?'':'s'}</span>`:'<span>Not yet sent</span>'}</div>${r.notes?`<p>${esc(r.notes)}</p>`:''}</div><div class="media-card-actions"><button class="primary" data-media-send="${r.id}">Send to Customer</button><button class="secondary" data-media-open="${r.id}">Open</button><button class="secondary media-delete" data-media-delete="${r.id}">Delete</button></div></article>`).join('');bindCardActions();hydratePreviews();}
function bindCardActions(){document.querySelectorAll('[data-media-send]').forEach(b=>b.onclick=()=>openSend(b.dataset.mediaSend));document.querySelectorAll('[data-media-open]').forEach(b=>b.onclick=()=>openFile(b.dataset.mediaOpen));document.querySelectorAll('[data-media-delete]').forEach(b=>b.onclick=()=>removeRecord(b.dataset.mediaDelete));}
async function openFile(id){const rec=records.find(r=>r.id===id);if(!rec)return;const url=await getUrl(rec);if(url)window.open(url,'_blank')}
async function removeRecord(id){const rec=records.find(r=>r.id===id);if(!rec||!confirm(`Delete ${rec.title} from the Media Centre?`))return;records=records.filter(r=>r.id!==id);saveMeta();if(objectUrls.has(id)){URL.revokeObjectURL(objectUrls.get(id));objectUrls.delete(id)};try{await deleteBlob(id)}catch(e){console.warn(e)}render();}
function defaultMessage(rec){const first=rec.customerName?rec.customerName.split(/\s+/)[0]:'';return `${first?`Hi ${first},\n\n`:'Hi,\n\n'}Here is the ${rec.title.toLowerCase()} for your ${displayReg(rec.reg)} from our workshop.\n\nKind regards\nGarage Gurus`}
function openSend(id){const rec=records.find(r=>r.id===id);if(!rec)return;activeSendId=id;$('mediaSendTitle').textContent=rec.title;$('mediaSendSub').textContent=`${displayReg(rec.reg)}${rec.customerName?' · '+rec.customerName:''}`;$('mediaSendPhone').value=rec.phone||'';$('mediaSendEmail').value=rec.email||'';$('mediaSendMessage').value=defaultMessage(rec);$('mediaSendModal').classList.remove('hidden');}
function closeSend(){$('mediaSendModal')?.classList.add('hidden');activeSendId=null;}
function activeRec(){return records.find(r=>r.id===activeSendId)}
function markSent(rec,method){rec.sendLog=rec.sendLog||[];rec.sendLog.push({method,date:new Date().toISOString()});rec.phone=$('mediaSendPhone').value.trim();rec.email=$('mediaSendEmail').value.trim();saveMeta();render();}
function sendText(){const rec=activeRec();if(!rec)return;const phone=$('mediaSendPhone').value.trim().replace(/\s/g,'');if(!phone){alert('Please enter the customer mobile number.');return}const message=$('mediaSendMessage').value;markSent(rec,'Text prepared');window.location.href=`sms:${encodeURIComponent(phone)}?&body=${encodeURIComponent(message)}`;}
function sendEmail(){const rec=activeRec();if(!rec)return;const email=$('mediaSendEmail').value.trim();if(!email){alert('Please enter the customer email address.');return}const subject=`Vehicle video / media – ${displayReg(rec.reg)}`;const message=$('mediaSendMessage').value;markSent(rec,'Email prepared');window.location.href=`mailto:${encodeURIComponent(email)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(message)}`;}
async function shareFile(){const rec=activeRec();if(!rec)return;const blob=await getBlob(rec.id);if(!blob){alert('The media file is no longer available on this device.');return}const file=new File([blob],rec.fileName||'vehicle-media',{type:rec.mime||blob.type});const data={title:rec.title,text:$('mediaSendMessage').value,files:[file]};if(navigator.canShare&&navigator.canShare({files:[file]})&&navigator.share){try{await navigator.share(data);markSent(rec,'Device share');return}catch(e){if(e.name==='AbortError')return}}alert('Direct file sharing is not supported in this browser. Use Text or Email to prepare the message, or open Workshop AI on a phone/tablet that supports file sharing.');}
function bind(){if(!$('mediaCentreScreen'))return;$('mediaAddBtn').onclick=openAdd;$('mediaModalClose').onclick=$('mediaCancelBtn').onclick=closeAdd;$('mediaSaveBtn').onclick=saveRecord;$('mediaSendClose').onclick=closeSend;$('mediaSendTextBtn').onclick=sendText;$('mediaSendEmailBtn').onclick=sendEmail;$('mediaShareFileBtn').onclick=shareFile;$('mediaSearch').addEventListener('input',render);$('mediaTypeFilter').addEventListener('change',render);$('mediaStatusFilter').addEventListener('change',render);$('mediaCustomer').addEventListener('change',()=>{const c=selectedCustomer();if(!c)return;$('mediaPhone').value=c.mobile||c.home||c.work||'';$('mediaEmail').value=c.email||'';if(!$('mediaReg').value){const r=customerVehicleReg(c);if(r)$('mediaReg').value=r}});$('mediaReg').addEventListener('input',e=>e.target.value=e.target.value.toUpperCase());document.addEventListener('wai096:crm-updated',populateCustomers);render();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
window.WorkshopMediaCentre={render};
})();
