/* Workshop AI WAI-102.0 — Daily Operational Gross Profit & Historical Reporting */
(function(){
'use strict';
const money=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(Number(n)||0);
const round=n=>Math.round(((Number(n)||0)+Number.EPSILON)*100)/100;
const isoDay=d=>String(d||'').slice(0,10);
const today=()=>new Date().toISOString().slice(0,10);
const readInvoices=()=>window.WAI099FinanceBridge?.getInvoices?.()||[];
function calcLine(l){const q=Math.max(0,Number(l.qty)||0),sell=Math.max(0,Number(l.sell)||0),cost=Math.max(0,Number(l.cost)||0),gross=q*sell;let disc=l.discountType==='%'?gross*(Math.max(0,Number(l.discount)||0)/100):Math.max(0,Number(l.discount)||0);disc=Math.min(gross,disc);const net=round(gross-disc),lineCost=round(q*cost),vat=round(net*(Math.max(0,Number(l.vat)||0)/100));return{net,cost:lineCost,gp:round(net-lineCost),vat,category:l.type||'Other'};}
function calcInvoice(inv){return (inv.lines||[]).reduce((a,l)=>{const x=calcLine(l);a.sales=round(a.sales+x.net);a.cost=round(a.cost+x.cost);a.vat=round(a.vat+x.vat);a.gp=round(a.sales-a.cost);a.breakdown[x.category]=round((a.breakdown[x.category]||0)+x.gp);return a},{sales:0,cost:0,gp:0,vat:0,breakdown:{}});}
function firstAuditDay(inv,action){const a=(inv.audit||[]).find(x=>x.action===action);return isoDay(a?.at);}
function issueDay(inv){return firstAuditDay(inv,'Invoice issued')||(['Invoice Issued','Part Paid','Paid','Archived','Credited'].includes(inv.status)?isoDay(inv.date):'');}
function creditDay(inv){return firstAuditDay(inv,'Credit note created');}
function empty(day){return{date:day,invoices:0,credits:0,sales:0,cost:0,gp:0,vat:0,gpPct:0,breakdown:{Labour:0,Parts:0,Oil:0,MOT:0,Consumables:0,Sublet:0,Other:0}};}
function add(target,x,sign=1){target.sales=round(target.sales+sign*x.sales);target.cost=round(target.cost+sign*x.cost);target.vat=round(target.vat+sign*x.vat);Object.entries(x.breakdown||{}).forEach(([k,v])=>target.breakdown[k]=round((target.breakdown[k]||0)+sign*v));target.gp=round(target.sales-target.cost);target.gpPct=target.sales?round(target.gp/target.sales*100):0;}
function dailyHistory(){const map={};readInvoices().forEach(inv=>{const x=calcInvoice(inv),issued=issueDay(inv),credited=creditDay(inv);if(issued){map[issued]??=empty(issued);add(map[issued],x,1);map[issued].invoices++;}if(credited){map[credited]??=empty(credited);add(map[credited],x,-1);map[credited].credits++;}});return Object.values(map).sort((a,b)=>a.date.localeCompare(b.date));}
function todaySnapshot(){return dailyHistory().find(x=>x.date===today())||empty(today());}
function dateStartOfWeek(s){const d=new Date(s+'T12:00:00');const day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);return d.toISOString().slice(0,10);}
function group(rows,mode){const map={};rows.forEach(r=>{const key=mode==='week'?dateStartOfWeek(r.date):r.date.slice(0,7);map[key]??={key,invoices:0,credits:0,sales:0,cost:0,gp:0,vat:0,gpPct:0,days:0,breakdown:{}};const g=map[key];g.invoices+=r.invoices;g.credits+=r.credits;g.days++;add(g,r,1);});return Object.values(map).sort((a,b)=>a.key.localeCompare(b.key));}
function ensurePanel(){if(document.getElementById('operationalGpReport'))return;const sub=document.querySelector('#financeCentreScreen .finance-subnav');const builder=document.getElementById('invoiceBuilder');if(!sub||!builder)return;const btn=document.createElement('button');btn.dataset.financePanel='operationalGpReport';btn.textContent='Operational GP Report';sub.appendChild(btn);const panel=document.createElement('div');panel.id='operationalGpReport';panel.className='finance-panel';panel.innerHTML='<div id="operationalGpHost"></div>';builder.parentNode.insertBefore(panel,builder);btn.addEventListener('click',()=>{document.querySelectorAll('#financeCentreScreen .finance-panel').forEach(p=>p.classList.toggle('active',p.id==='operationalGpReport'));document.querySelectorAll('#financeCentreScreen [data-finance-panel]').forEach(b=>b.classList.toggle('active',b.dataset.financePanel==='operationalGpReport'));renderReport();});}
function rowHtml(r,label){return `<tr><td>${label}</td><td>${r.invoices}</td><td>${r.credits}</td><td>${money(r.sales)}</td><td>${money(r.cost)}</td><td><strong>${money(r.gp)}</strong></td><td>${Number(r.gpPct||0).toFixed(1)}%</td></tr>`;}
function renderReport(){const host=document.getElementById('operationalGpHost');if(!host)return;const rows=dailyHistory(),weeks=group(rows,'week'),months=group(rows,'month');const selected=document.getElementById('ogpView')?.value||'daily';const data=selected==='weekly'?weeks:selected==='monthly'?months:rows;const latestMonths=months.slice(-12).reverse();const current=months.at(-1),previous=months.at(-2);const change=current&&previous?round(current.gp-previous.gp):0;host.innerHTML=`<div class="finance-card ogp-report"><div class="ogp-head"><div><p class="finance-eyebrow">WAI-105.4 · FINANCIAL INTELLIGENCE</p><h3>Operational Gross Profit</h3><p class="finance-note">Issued invoice sales ex VAT less direct labour, parts, oil, MOT, consumables and sublet costs. Credits are deducted on the date raised.</p></div><select id="ogpView"><option value="daily" ${selected==='daily'?'selected':''}>Daily</option><option value="weekly" ${selected==='weekly'?'selected':''}>Weekly</option><option value="monthly" ${selected==='monthly'?'selected':''}>Monthly</option></select></div><div class="finance-kpis"><div><small>Operational GP today</small><strong>${money(todaySnapshot().gp)}</strong></div><div><small>Current month</small><strong>${money(current?.gp||0)}</strong></div><div><small>Vs previous month</small><strong>${change>=0?'+':''}${money(change)}</strong></div><div><small>Current GP %</small><strong>${Number(current?.gpPct||0).toFixed(1)}%</strong></div></div><div class="invoice-table-wrap"><table class="invoice-register operational-gp-table"><thead><tr><th>${selected==='daily'?'Date':selected==='weekly'?'Week commencing':'Month'}</th><th>Invoices</th><th>Credits</th><th>Sales ex VAT</th><th>Direct costs</th><th>Operational GP</th><th>GP %</th></tr></thead><tbody>${data.slice().reverse().map(r=>rowHtml(r,r.date||r.key)).join('')||'<tr><td colspan="7">No issued invoice history yet.</td></tr>'}</tbody></table></div><h4>Monthly comparison</h4><div class="invoice-table-wrap"><table class="invoice-register operational-gp-table"><thead><tr><th>Month</th><th>Invoices</th><th>Credits</th><th>Sales ex VAT</th><th>Direct costs</th><th>Operational GP</th><th>GP %</th></tr></thead><tbody>${latestMonths.map(r=>rowHtml(r,r.key)).join('')||'<tr><td colspan="7">No monthly history yet.</td></tr>'}</tbody></table></div></div>`;document.getElementById('ogpView').onchange=renderReport;}
function refresh(){ensurePanel();renderReport();window.dispatchEvent(new CustomEvent('wai-operational-gp-updated',{detail:todaySnapshot()}));}
window.WAI1020OperationalGP={dailyHistory,todaySnapshot,weekly:()=>group(dailyHistory(),'week'),monthly:()=>group(dailyHistory(),'month'),renderReport};
document.addEventListener('DOMContentLoaded',refresh);window.addEventListener('wai-finance-updated',refresh);
})();
