(function(){
'use strict';
const SETTINGS_KEY='workshopAIReviewCentreSettingsV1';
const SENT_KEY='workshopAIReviewCentreSentV1';
const DONT_SEND_KEY='workshopAIReviewCentreDontSendV1';
let activeKey=null;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const normReg=s=>String(s||'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const displayReg=s=>{const r=normReg(s);return r.length>4?r.slice(0,-3)+' '+r.slice(-3):r};
const todayMonth=()=>new Date().toISOString().slice(0,7);
function loadSettings(){try{return {...defaults(),...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')}}catch(_){return defaults()}}
function defaults(){return {google:'',trustpilot:'',facebook:'',other:'',message:'Hi {firstName},\n\nThank you for choosing us to look after your {reg}. We hope you were happy with the service you received.\n\nIf you have a moment, we would really appreciate a review:\n{links}\n\nThank you,\nGarage Gurus'}}
function loadSent(){try{const x=JSON.parse(localStorage.getItem(SENT_KEY)||'{}');return x&&typeof x==='object'?x:{}}catch(_){return{}}}
function saveSent(x){localStorage.setItem(SENT_KEY,JSON.stringify(x))}
function loadDontSend(){try{const x=JSON.parse(localStorage.getItem(DONT_SEND_KEY)||'{}');return x&&typeof x==='object'?x:{}}catch(_){return{}}}
function saveDontSend(x){localStorage.setItem(DONT_SEND_KEY,JSON.stringify(x))}
function allJobs(){const keys=['workshopAIJobsV27','workshopAIJobsV26','workshopAIJobsV25','workshopAIJobsV24','workshopAIJobsV23','workshopAIJobsV22','workshopAIJobsV21','pcaJobsV11','pcaJobsV10'];for(const k of keys){try{const a=JSON.parse(localStorage.getItem(k)||'null');if(Array.isArray(a))return a}catch(_){}}return Array.isArray(window.jobs)?window.jobs:[]}
function crmCustomers(){try{return JSON.parse(localStorage.getItem('wai096_crm')||'{}').customers||[]}catch(_){return[]}}
function fullName(c){return [c?.title,c?.firstName,c?.surname].filter(Boolean).join(' ')||c?.company||''}
function findCustomer(j){const cs=crmCustomers();if(j.customerId){const c=cs.find(x=>x.id===j.customerId);if(c)return c}const reg=normReg(j.reg);return cs.find(c=>(c.vehicles||[]).some(v=>normReg(v.registration)===reg))||null}
function completedDate(j){return String(j.completedAt||j.finishedAt||'').slice(0,10)}
function isCompleted(j){return !!completedDate(j)||(String(j.status||'').includes('Ready'))||(String(j.status||'').includes('Collected'))||(String(j.status||'').includes('Closed'))}
function rowKey(j){return String(j.id||j.jobNo||`${normReg(j.reg)}-${completedDate(j)}`)}
function rows(){const month=$('reviewMonth')?.value||todayMonth(), q=String($('reviewSearch')?.value||'').trim().toLowerCase(), status=$('reviewStatusFilter')?.value||'all', sent=loadSent(),dontSend=loadDontSend();return allJobs().filter(isCompleted).map(j=>{const c=findCustomer(j),name=j.customer||fullName(c)||'Customer',phone=j.phone||c?.mobile||c?.home||c?.work||'',email=j.customerEmail||c?.email||'',date=completedDate(j)||String(j.bookingDate||j.createdAt||'').slice(0,10),key=rowKey(j),log=sent[key]||null;return {j,c,name,phone,email,date,key,log}}).filter(x=>!dontSend[x.key]).filter(x=>x.date&&x.date.slice(0,7)===month).filter(x=>!q||`${x.name} ${x.j.reg||''} ${x.phone} ${x.email}`.toLowerCase().includes(q)).filter(x=>status==='all'||(status==='sent'?!!x.log:!x.log)).sort((a,b)=>b.date.localeCompare(a.date))}
function dateLabel(s){try{return new Date(s+'T12:00:00').toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}catch(_){return s}}
function settingsLinks(s){return [['Google',s.google],['Trustpilot',s.trustpilot],['Facebook',s.facebook],['Review',s.other]].filter(x=>x[1])}
function firstName(name){return String(name||'').trim().split(/\s+/)[0]||'there'}
function messageFor(x){const s=loadSettings(),links=settingsLinks(s).map(([n,u])=>`${n}: ${u}`).join('\n');return String(s.message||defaults().message).replaceAll('{firstName}',firstName(x.name)).replaceAll('{reg}',displayReg(x.j.reg)||'vehicle').replaceAll('{links}',links||'Please ask the service team for our review link.')}
function allEligibleThisMonth(){const month=$('reviewMonth')?.value||todayMonth();return allJobs().filter(isCompleted).filter(j=>{const d=completedDate(j)||String(j.bookingDate||j.createdAt||'').slice(0,10);return d.slice(0,7)===month})}
function render(){if(!$('reviewTableBody'))return;const data=rows(),sent=loadSent(),dontSend=loadDontSend(),eligible=allEligibleThisMonth();$('reviewEligibleCount').textContent=eligible.length;$('reviewSentCount').textContent=eligible.filter(j=>sent[rowKey(j)]).length;$('reviewAwaitingCount').textContent=eligible.filter(j=>!sent[rowKey(j)]&&!dontSend[rowKey(j)]).length;$('reviewLinkCount').textContent=settingsLinks(loadSettings()).length;$('reviewEmpty').classList.toggle('hidden',data.length>0);$('reviewTableBody').innerHTML=data.map(x=>`<tr><td>${esc(dateLabel(x.date))}</td><td><strong>${esc(x.name)}</strong><small>${esc(x.j.jobNo||'Workshop job')}</small></td><td><span class="review-reg">${esc(displayReg(x.j.reg))}</span><small>${esc([x.j.make,x.j.model].filter(Boolean).join(' '))}</small></td><td><span>${esc(x.phone||'No mobile')}</span><small>${esc(x.email||'No email')}</small></td><td>${x.log?`<span class="review-status sent">Sent</span><small>${esc(x.log.method)} · ${esc(new Date(x.log.date).toLocaleString('en-GB'))}</small>`:'<span class="review-status awaiting">Awaiting</span>'}</td><td><div class="review-actions"><button class="primary" data-review-send="${esc(x.key)}" ${(!x.phone&&!x.email)?'disabled':''}>Send Request</button>${!x.log?`<button class="secondary review-dont-send" data-review-dont-send="${esc(x.key)}">Don’t Send</button>`:`<button class="secondary" data-review-reset="${esc(x.key)}">Mark Awaiting</button>`}</div></td></tr>`).join('');document.querySelectorAll('[data-review-send]').forEach(b=>b.onclick=()=>openSend(b.dataset.reviewSend));document.querySelectorAll('[data-review-reset]').forEach(b=>b.onclick=()=>resetSent(b.dataset.reviewReset));document.querySelectorAll('[data-review-dont-send]').forEach(b=>b.onclick=()=>markDontSend(b.dataset.reviewDontSend));}
function currentRow(){return rows().find(x=>x.key===activeKey)||(()=>{const j=allJobs().find(j=>rowKey(j)===activeKey);if(!j)return null;const c=findCustomer(j);return {j,c,name:j.customer||fullName(c)||'Customer',phone:j.phone||c?.mobile||c?.home||c?.work||'',email:j.customerEmail||c?.email||'',date:completedDate(j),key:activeKey}})()}
function openSettings(){const s=loadSettings();$('reviewGoogle').value=s.google||'';$('reviewTrustpilot').value=s.trustpilot||'';$('reviewFacebook').value=s.facebook||'';$('reviewOther').value=s.other||'';$('reviewMessage').value=s.message||defaults().message;$('reviewSettingsModal').classList.remove('hidden')}
function closeSettings(){$('reviewSettingsModal').classList.add('hidden')}
function saveSettings(){const s={google:$('reviewGoogle').value.trim(),trustpilot:$('reviewTrustpilot').value.trim(),facebook:$('reviewFacebook').value.trim(),other:$('reviewOther').value.trim(),message:$('reviewMessage').value};localStorage.setItem(SETTINGS_KEY,JSON.stringify(s));closeSettings();render()}
function openSend(key){activeKey=key;const x=currentRow();if(!x)return;const links=settingsLinks(loadSettings());if(!links.length&&confirm('No review links are saved yet. Open Review Links & Message now?')){openSettings();activeKey=null;return}$('reviewSendTitle').textContent=`Review request · ${displayReg(x.j.reg)}`;$('reviewSendSub').textContent=x.name;$('reviewSendPhone').value=x.phone||'';$('reviewSendEmail').value=x.email||'';$('reviewSendMessage').value=messageFor(x);$('reviewSendModal').classList.remove('hidden')}
function closeSend(){$('reviewSendModal').classList.add('hidden');activeKey=null}
function markSent(method){const x=currentRow();if(!x)return;const sent=loadSent();sent[x.key]={date:new Date().toISOString(),method,customer:x.name,reg:normReg(x.j.reg)};saveSent(sent);render()}
function sendText(){const x=currentRow();if(!x)return;const phone=$('reviewSendPhone').value.trim().replace(/\s/g,'');if(!phone){alert('Please enter the customer mobile number.');return}const msg=$('reviewSendMessage').value;markSent('Text');window.location.href=`sms:${encodeURIComponent(phone)}?&body=${encodeURIComponent(msg)}`}
function sendEmail(){const x=currentRow();if(!x)return;const email=$('reviewSendEmail').value.trim();if(!email){alert('Please enter the customer email address.');return}const subject='Thank you for visiting our workshop';const msg=$('reviewSendMessage').value;markSent('Email');window.location.href=`mailto:${encodeURIComponent(email)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(msg)}`}
function resetSent(key){const sent=loadSent();delete sent[key];saveSent(sent);render()}
function markDontSend(key){const j=allJobs().find(j=>rowKey(j)===key);if(!j)return;const c=findCustomer(j),name=j.customer||fullName(c)||'Customer',reg=normReg(j.reg);if(!confirm(`Remove ${name}${reg?` · ${displayReg(reg)}`:''} from the Review Centre?`))return;const dontSend=loadDontSend();dontSend[key]={date:new Date().toISOString(),customer:name,reg};saveDontSend(dontSend);render()}
function bind(){if(!$('reviewCentreScreen'))return;$('reviewMonth').value=todayMonth();$('reviewLinksBtn').onclick=openSettings;$('reviewSettingsClose').onclick=$('reviewSettingsCancel').onclick=closeSettings;$('reviewSettingsSave').onclick=saveSettings;$('reviewSendClose').onclick=closeSend;$('reviewSendText').onclick=sendText;$('reviewSendEmail').onclick=sendEmail;$('reviewMonth').onchange=render;$('reviewSearch').oninput=render;$('reviewStatusFilter').onchange=render;render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
window.WorkshopReviewCentre={render};
})();
