
(function(){
'use strict';
const KEY='wai096_crm';
const DEFAULT_MAINT=[['MOT',12],['Service',12],['Brake Fluid',24],['Coolant',48],['Cambelt',60],['Timing Chain Inspection',24],['Spark Plugs',48],['Gearbox Oil',48],['Haldex',36],['Transfer Box Oil',48],['Differential Oil',48],['Air Conditioning',24],['Battery Health',12],['Brake Inspection',12],['Wheel Alignment',12],['Tyre Rotation',12],['Air Filter',24],['Cabin Filter',12],['Fuel Filter',24],['Wiper Blades',12]];
let db=load(), selectedId=null, activeTab='overview';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x&&x.customers)return x}catch(e){}return {customers:[],communications:[],version:'WAI-096'} }
function save(){localStorage.setItem(KEY,JSON.stringify(db));document.dispatchEvent(new CustomEvent('wai096:crm-updated'));}
function id(prefix){return prefix+'-'+Date.now().toString(36).toUpperCase()+Math.random().toString(36).slice(2,5).toUpperCase()}
function normReg(v){return String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'')}
function displayReg(v){let r=normReg(v);return r.length>4?r.slice(0,-3)+' '+r.slice(-3):r}
function dateAddMonths(date,months){if(!date)return'';let d=new Date(date+'T12:00:00');d.setMonth(d.getMonth()+Number(months||0));return d.toISOString().slice(0,10)}
function daysUntil(date){if(!date)return null;return Math.ceil((new Date(date+'T23:59:59')-new Date())/86400000)}
function maintStatus(m){const d=daysUntil(m.nextDueDate);if(d===null)return 'amber';if(d<0)return 'red';if(d<=60)return 'amber';return 'green'}
function vehicleScore(v){let items=v.maintenance||[];if(!items.length)return 50;let total=0;items.forEach(m=>total+=maintStatus(m)==='green'?100:maintStatus(m)==='amber'?65:20);let score=total/items.length;let outstanding=(v.outstanding||[]).filter(x=>x.status!=='Completed'&&x.status!=='Declined').length;return Math.max(0,Math.round(score-outstanding*4))}
function customerHealth(c){let vs=(c.vehicles||[]).map(vehicleScore);let base=vs.length?vs.reduce((a,b)=>a+b,0)/vs.length:65;let contact=(c.mobile||c.home||c.work)&&c.email?5:0;let response=c.missedAppointments?Math.max(-15,-5*c.missedAppointments):5;let overdue=(c.vehicles||[]).flatMap(v=>v.outstanding||[]).filter(x=>x.status==='Outstanding').length;return Math.max(0,Math.min(100,Math.round(base+contact+response-overdue*3)))}
function loyalty(c){if(c.loyaltyOverride)return c.loyaltyOverride;let spend=Number(c.lifetimeSpend||0), visits=Number(c.visitCount||0), years=Math.max(0,(Date.now()-new Date(c.customerSince||Date.now()))/31557600000);if(spend>=5000||visits>=15||years>=7)return'Gold';if(spend>=1500||visits>=5||years>=2)return'Silver';return'Bronze'}
function customerName(c){return [c.title,c.firstName,c.surname].filter(Boolean).join(' ')||c.company||'Unnamed customer'}
function allJobs(){try{return typeof jobs!=='undefined'&&Array.isArray(jobs)?jobs:JSON.parse(localStorage.getItem('jobs')||'[]')}catch(e){return[]}}
function linkedJobs(v){return allJobs().filter(j=>normReg(j.reg)===normReg(v.registration)).sort((a,b)=>new Date(b.completedAt||b.createdAt)-new Date(a.completedAt||a.createdAt))}
function stats(){const cs=db.customers, vehicles=cs.flatMap(c=>c.vehicles||[]), due=vehicles.flatMap(v=>(v.maintenance||[]).filter(m=>maintStatus(m)!=='green')).length;return {customers:cs.length,vehicles:vehicles.length,due,health:cs.length?Math.round(cs.reduce((a,c)=>a+customerHealth(c),0)/cs.length):0}}
function render(){if(!$('crmScreen'))return;const st=stats();$('crmStats').innerHTML=[['Customers',st.customers],['Linked Vehicles',st.vehicles],['Maintenance Alerts',st.due],['Average Customer Health',st.health+'%']].map(x=>`<div class="stat-card"><strong>${x[1]}</strong><span>${x[0]}</span></div>`).join('');renderList();renderWorkspace();}
function filtered(){let q=($('crmSearch')?.value||'').toLowerCase().replace(/\s/g,''), f=$('crmFilter')?.value||'all';return db.customers.filter(c=>{let text=[c.id,customerName(c),c.company,c.mobile,c.home,c.work,c.email,c.postcode,...(c.vehicles||[]).map(v=>v.registration)].join(' ').toLowerCase().replace(/\s/g,'');let ok=!q||text.includes(q);if(f==='active')ok=ok&&c.status!=='Inactive';if(f==='inactive')ok=ok&&c.status==='Inactive';if(f==='gold')ok=ok&&loyalty(c)==='Gold';if(f==='due')ok=ok&&(c.vehicles||[]).some(v=>(v.maintenance||[]).some(m=>maintStatus(m)!=='green'));return ok}).sort((a,b)=>customerName(a).localeCompare(customerName(b)))}
function renderList(){const list=filtered();$('crmResultCount').textContent=list.length+' result'+(list.length===1?'':'s');$('crmCustomerList').innerHTML=list.length?list.map(c=>`<div class="crm-customer-row ${selectedId===c.id?'active':''}" data-customer="${c.id}"><h3>${esc(customerName(c))}</h3><div class="crm-mini">${esc(c.id)} · ${esc(loyalty(c))} · Health ${customerHealth(c)}%</div><div class="crm-mini">${esc(c.mobile||c.home||c.email||'No contact details')} · ${(c.vehicles||[]).map(v=>displayReg(v.registration)).join(', ')||'No vehicles'}</div></div>`).join(''):'<p class="muted">No matching customers.</p>';document.querySelectorAll('[data-customer]').forEach(el=>el.onclick=()=>{selectedId=el.dataset.customer;activeTab='overview';render()})}
function renderWorkspace(){const c=db.customers.find(x=>x.id===selectedId);if(!c){$('crmWorkspace').innerHTML='<div class="card crm-empty"><h2>Select a customer</h2><p class="muted">Open a customer to view health, vehicles, maintenance, communications and history.</p></div>';return}let outstanding=(c.vehicles||[]).flatMap(v=>(v.outstanding||[]).filter(x=>x.status==='Outstanding'));$('crmWorkspace').innerHTML=`<div class="card"><div class="crm-profile-head"><div><span class="crm-eyebrow">${esc(c.id)}</span><h2>${esc(customerName(c))}</h2><p>${esc(c.address1||'')}${c.address1?', ':''}${esc(c.town||'')} ${esc(c.postcode||'')}</p><div class="crm-badges"><span class="crm-badge ${loyalty(c).toLowerCase()}">${loyalty(c)} customer</span>${(c.tags||[]).map(t=>`<span class="crm-badge">${esc(t)}</span>`).join('')}</div></div><div class="crm-profile-actions"><button class="secondary crm-small-btn" id="crmSummaryBtn">Summarise Customer</button><button class="secondary crm-small-btn" id="crmEditBtn">Edit</button><button class="primary crm-small-btn" id="crmAddVehicleBtn">+ Vehicle</button></div></div><div class="crm-score-grid"><div class="crm-score-card"><span>Customer Health</span><strong>${customerHealth(c)}%</strong></div><div class="crm-score-card"><span>Loyalty</span><strong>${loyalty(c)}</strong></div><div class="crm-score-card"><span>Lifetime Spend</span><strong>£${Number(c.lifetimeSpend||0).toLocaleString('en-GB',{minimumFractionDigits:0,maximumFractionDigits:0})}</strong></div><div class="crm-score-card"><span>Outstanding Work</span><strong>£${outstanding.reduce((a,x)=>a+Number(x.value||0),0).toLocaleString('en-GB')}</strong></div></div><div class="crm-tabs">${[['overview','Overview'],['vehicles','Vehicles'],['maintenance','Maintenance'],['timeline','Timeline'],['communications','Communications'],['documents','Documents']].map(x=>`<button class="secondary ${activeTab===x[0]?'active':''}" data-crm-tab="${x[0]}">${x[1]}</button>`).join('')}</div><div id="crmTabBody"></div></div>`;document.querySelectorAll('[data-crm-tab]').forEach(b=>b.onclick=()=>{activeTab=b.dataset.crmTab;renderWorkspace()});$('crmEditBtn').onclick=()=>openCustomerModal(c);$('crmAddVehicleBtn').onclick=()=>openVehicleModal(c);$('crmSummaryBtn').onclick=()=>showSummary(c);renderTab(c)}
function renderTab(c){let body=$('crmTabBody');if(activeTab==='overview'){let next=[];(c.vehicles||[]).forEach(v=>(v.maintenance||[]).filter(m=>maintStatus(m)!=='green').forEach(m=>next.push({reg:v.registration,...m,status:maintStatus(m)})));next.sort((a,b)=>(a.nextDueDate||'9999').localeCompare(b.nextDueDate||'9999'));body.innerHTML=`<div class="crm-section-grid"><div><h3>Contact & Preferences</h3><p><strong>Mobile:</strong> ${esc(c.mobile||'Not entered')}</p><p><strong>Home:</strong> ${esc(c.home||'Not entered')}</p><p><strong>Work:</strong> ${esc(c.work||'Not entered')}</p><p><strong>Email:</strong> ${esc(c.email||'Not entered')}</p><p><strong>Preferred:</strong> ${esc(c.preferredContact||'Not set')} · ${esc(c.preferredTime||'Anytime')}</p><p><strong>Relationship:</strong> ${esc((c.preferences||[]).join(', ')||'No preferences recorded')}</p></div><div><h3>Next Conversation</h3>${next.slice(0,5).map(x=>`<div class="crm-alert"><strong>${displayReg(x.reg)} · ${esc(x.name)}</strong><br>${x.nextDueDate?'Due '+new Date(x.nextDueDate).toLocaleDateString('en-GB'):'Due date missing'} · <span class="crm-status ${x.status}">${x.status.toUpperCase()}</span></div>`).join('')||'<p class="muted">No maintenance alerts.</p>'}${c.notes?`<div class="crm-note"><strong>Important note</strong><br>${esc(c.notes)}</div>`:''}</div></div>`}
else if(activeTab==='vehicles'){body.innerHTML=(c.vehicles||[]).map(v=>vehicleCard(c,v)).join('')||'<p class="muted">No vehicles linked yet.</p>';document.querySelectorAll('[data-edit-vehicle]').forEach(b=>b.onclick=()=>openVehicleModal(c,c.vehicles.find(v=>v.id===b.dataset.editVehicle)));document.querySelectorAll('[data-delete-vehicle]').forEach(b=>b.onclick=()=>{if(confirm('Remove this vehicle from the CRM?')){c.vehicles=c.vehicles.filter(v=>v.id!==b.dataset.deleteVehicle);save();render()}})}
else if(activeTab==='maintenance'){let rows=(c.vehicles||[]).flatMap(v=>(v.maintenance||[]).map(m=>({v,m})));body.innerHTML=`<h3>Vehicle Maintenance Centre</h3><table class="crm-due-table"><thead><tr><th>Vehicle</th><th>Item</th><th>Last completed</th><th>Next due</th><th>Mileage due</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(({v,m})=>`<tr><td>${displayReg(v.registration)}</td><td>${esc(m.name)}</td><td>${m.lastDate?new Date(m.lastDate).toLocaleDateString('en-GB'):'—'}</td><td>${m.nextDueDate?new Date(m.nextDueDate).toLocaleDateString('en-GB'):'—'}</td><td>${m.nextDueMileage||'—'}</td><td><span class="crm-status ${maintStatus(m)}">${maintStatus(m).toUpperCase()}</span></td><td><button class="secondary crm-small-btn" data-maint="${v.id}|${m.id}">Update</button></td></tr>`).join('')}</tbody></table>`;document.querySelectorAll('[data-maint]').forEach(b=>b.onclick=()=>{let [vid,mid]=b.dataset.maint.split('|'),v=c.vehicles.find(x=>x.id===vid),m=v.maintenance.find(x=>x.id===mid);openMaintenanceModal(c,v,m)})}
else if(activeTab==='timeline'){let events=[];(c.vehicles||[]).forEach(v=>{linkedJobs(v).forEach(j=>events.push({date:j.completedAt||j.createdAt,title:`${displayReg(v.registration)} · ${j.workRequired||j.status||'Workshop visit'}`,detail:`${j.technician||''} ${j.actualHours?`· ${Number(j.actualHours).toFixed(2)} hrs`:''}`}));(v.lifeStory||[]).forEach(e=>events.push(e))});(c.timeline||[]).forEach(e=>events.push(e));events.sort((a,b)=>new Date(b.date)-new Date(a.date));body.innerHTML=`<h3>Customer & Vehicle Life Story</h3>${events.map(e=>`<div class="crm-timeline-item"><strong>${new Date(e.date).toLocaleDateString('en-GB')} · ${esc(e.title)}</strong><p>${esc(e.detail||'')}</p></div>`).join('')||'<p class="muted">No timeline entries yet.</p>'}`}
else if(activeTab==='communications'){body.innerHTML=`<div class="crm-profile-head"><h3>Communication Timeline</h3><button class="primary crm-small-btn" id="crmAddComm">+ Add Contact</button></div>${(c.communications||[]).slice().reverse().map(x=>`<div class="crm-timeline-item"><strong>${new Date(x.date).toLocaleString('en-GB')} · ${esc(x.method)} · ${esc(x.outcome||'')}</strong><p>${esc(x.note)}</p></div>`).join('')||'<p class="muted">No contact recorded.</p>'}`;$('crmAddComm').onclick=()=>openCommunicationModal(c)}
else if(activeTab==='documents'){body.innerHTML=`<div class="crm-profile-head"><h3>Document Centre</h3><button class="primary crm-small-btn" id="crmAddDoc">+ Add Document Reference</button></div><p class="muted">Store references to invoices, estimates, VHCs, warranty documents, photos and service records.</p>${(c.documents||[]).map(d=>`<div class="crm-timeline-item"><strong>${esc(d.type)} · ${esc(d.name)}</strong><p>${esc(d.note||'')}</p></div>`).join('')||'<p class="muted">No documents recorded.</p>'}`;$('crmAddDoc').onclick=()=>openDocumentModal(c)} }
function vehicleCard(c,v){let jobs=linkedJobs(v), alerts=(v.maintenance||[]).filter(m=>maintStatus(m)!=='green').length;return `<div class="crm-vehicle-card"><div class="crm-vehicle-head"><div><div class="crm-reg">${displayReg(v.registration)}</div><h3>${esc(v.make)} ${esc(v.model)} ${esc(v.variant||'')}</h3><p class="crm-mini">${esc(v.id)} · VIN ${esc(v.vin||'Not entered')}</p></div><div><span class="crm-badge">Condition ${vehicleScore(v)}%</span><button class="primary crm-small-btn" onclick="window.WorkshopCRMBridge.loadNewJob('${c.id}','${v.id}')">Load New Job</button><button class="secondary crm-small-btn" onclick="window.WorkshopCRMBridge.openMaintenance('${c.id}','${v.id}')">Maintenance Dates</button><button class="secondary crm-small-btn" data-edit-vehicle="${v.id}">Edit</button><button class="secondary crm-small-btn" data-delete-vehicle="${v.id}">Remove</button></div></div><div class="crm-vehicle-summary"><div><strong>${Number(v.mileage||0).toLocaleString('en-GB')}</strong><br><span class="crm-mini">Mileage</span></div><div><strong>${jobs.length}</strong><br><span class="crm-mini">Workshop visits</span></div><div><strong>${alerts}</strong><br><span class="crm-mini">Maintenance alerts</span></div></div><p><strong>Fuel:</strong> ${esc(v.fuel||'—')} · <strong>Transmission:</strong> ${esc(v.transmission||'—')} · <strong>Colour:</strong> ${esc(v.colour||'—')}</p></div>`}
function modal(html){let old=$('crmModal');if(old)old.remove();document.body.insertAdjacentHTML('beforeend',`<div id="crmModal" class="crm-modal"><div class="crm-modal-card">${html}</div></div>`);$('crmModal').onclick=e=>{if(e.target.id==='crmModal')e.currentTarget.remove()}}
function closeModal(){$('crmModal')?.remove()}
function field(label,id,value='',type='text',wide=false){return `<label class="${wide?'wide':''}">${label}<input id="${id}" type="${type}" value="${esc(value)}"></label>`}
function openCustomerModal(c){c=c||null;modal(`<div class="crm-modal-head"><h2>${c?'Edit':'New'} Customer</h2><button id="crmClose">×</button></div><div class="crm-field-grid">${field('Title','cfTitle',c?.title)}${field('First name','cfFirst',c?.firstName)}${field('Surname','cfSurname',c?.surname)}${field('Company','cfCompany',c?.company)}${field('Mobile','cfMobile',c?.mobile,'tel')}${field('Home telephone','cfHome',c?.home,'tel')}${field('Work telephone','cfWork',c?.work,'tel')}${field('Email','cfEmail',c?.email,'email')}${field('House name / number & street','cfAddress1',c?.address1,'text',true)}${field('Town / City','cfTown',c?.town)}${field('County','cfCounty',c?.county)}${field('Postcode','cfPostcode',c?.postcode)}<label>Preferred contact<select id="cfPreferred"><option>Mobile</option><option>Phone</option><option>Email</option><option>SMS</option><option>WhatsApp</option></select></label><label>Preferred time<select id="cfTime"><option>Anytime</option><option>Morning</option><option>Afternoon</option><option>Evening</option></select></label>${field('Customer since','cfSince',c?.customerSince||new Date().toISOString().slice(0,10),'date')}${field('Lifetime spend (£)','cfSpend',c?.lifetimeSpend||0,'number')}${field('Tags (comma separated)','cfTags',(c?.tags||[]).join(', '),'text',true)}${field('Preferences (comma separated)','cfPrefs',(c?.preferences||[]).join(', '),'text',true)}<label class="wide">Important notes<textarea id="cfNotes">${esc(c?.notes||'')}</textarea></label></div><div class="crm-form-actions"><button class="secondary" id="crmCancel">Cancel</button><button class="primary" id="crmSaveCustomer">Save Customer</button></div>`);$('crmClose').onclick=$('crmCancel').onclick=closeModal;if(c){$('cfPreferred').value=c.preferredContact||'Mobile';$('cfTime').value=c.preferredTime||'Anytime'}$('crmSaveCustomer').onclick=()=>{let x=c||{id:id('CUS'),createdAt:new Date().toISOString(),vehicles:[],communications:[],documents:[],timeline:[],status:'Active',visitCount:0,missedAppointments:0};Object.assign(x,{title:$('cfTitle').value.trim(),firstName:$('cfFirst').value.trim(),surname:$('cfSurname').value.trim(),company:$('cfCompany').value.trim(),mobile:$('cfMobile').value.trim(),home:$('cfHome').value.trim(),work:$('cfWork').value.trim(),email:$('cfEmail').value.trim(),address1:$('cfAddress1').value.trim(),town:$('cfTown').value.trim(),county:$('cfCounty').value.trim(),postcode:$('cfPostcode').value.toUpperCase().trim(),preferredContact:$('cfPreferred').value,preferredTime:$('cfTime').value,customerSince:$('cfSince').value,lifetimeSpend:Number($('cfSpend').value||0),tags:$('cfTags').value.split(',').map(x=>x.trim()).filter(Boolean),preferences:$('cfPrefs').value.split(',').map(x=>x.trim()).filter(Boolean),notes:$('cfNotes').value.trim()});if(!c)db.customers.push(x);selectedId=x.id;save();closeModal();render()}}
function defaultMaintenance(){return DEFAULT_MAINT.map(([name,months])=>({id:id('MNT'),name,intervalMonths:months,lastDate:'',lastMileage:'',nextDueDate:'',nextDueMileage:''}))}
function openVehicleModal(c,v){v=v||null;modal(`<div class="crm-modal-head"><h2>${v?'Edit':'Add'} Vehicle</h2><button id="crmClose">×</button></div><div class="crm-field-grid">${field('Registration','vfReg',v?.registration)}${field('VIN','vfVin',v?.vin)}${field('Make','vfMake',v?.make)}${field('Model','vfModel',v?.model)}${field('Variant','vfVariant',v?.variant)}${field('Year','vfYear',v?.year,'number')}${field('Colour','vfColour',v?.colour)}${field('Fuel','vfFuel',v?.fuel)}${field('Engine','vfEngine',v?.engine)}${field('Transmission','vfTrans',v?.transmission)}${field('Mileage','vfMileage',v?.mileage,'number')}${field('Date acquired','vfAcquired',v?.dateAcquired,'date')}${field('Warranty expiry','vfWarranty',v?.warrantyExpiry,'date')}</div><p class="muted">A complete maintenance schedule, including brake fluid every two years, will be created automatically for new vehicles.</p><div class="crm-form-actions"><button class="secondary" id="crmCancel">Cancel</button><button class="primary" id="crmSaveVehicle">Save Vehicle</button></div>`);$('crmClose').onclick=$('crmCancel').onclick=closeModal;$('vfReg').oninput=e=>e.target.value=e.target.value.toUpperCase();$('crmSaveVehicle').onclick=()=>{let reg=normReg($('vfReg').value);if(!reg){alert('Enter a registration');return}let duplicate=db.customers.flatMap(x=>(x.vehicles||[]).map(y=>({c:x,v:y}))).find(x=>normReg(x.v.registration)===reg&&x.v.id!==v?.id);if(duplicate&&!confirm(`This registration is already linked to ${customerName(duplicate.c)}. Add anyway?`))return;let x=v||{id:id('VEH'),maintenance:defaultMaintenance(),lifeStory:[],outstanding:[]};Object.assign(x,{registration:reg,vin:$('vfVin').value.toUpperCase().trim(),make:$('vfMake').value.trim(),model:$('vfModel').value.trim(),variant:$('vfVariant').value.trim(),year:$('vfYear').value,colour:$('vfColour').value.trim(),fuel:$('vfFuel').value.trim(),engine:$('vfEngine').value.trim(),transmission:$('vfTrans').value.trim(),mileage:Number($('vfMileage').value||0),dateAcquired:$('vfAcquired').value,warrantyExpiry:$('vfWarranty').value});if(!v)c.vehicles.push(x);save();closeModal();activeTab='vehicles';render()}}
function openMaintenanceModal(c,v,m){modal(`<div class="crm-modal-head"><h2>${displayReg(v.registration)} · ${esc(m.name)}</h2><button id="crmClose">×</button></div><div class="crm-field-grid">${field('Last completed date','mfLast',m.lastDate,'date')}${field('Last completed mileage','mfMileage',m.lastMileage,'number')}${field('Interval (months)','mfInterval',m.intervalMonths,'number')}${field('Next due date','mfNext',m.nextDueDate,'date')}${field('Next due mileage','mfNextMileage',m.nextDueMileage,'number')}</div><div class="crm-form-actions"><button class="secondary" id="crmCancel">Cancel</button><button class="primary" id="crmSaveMaint">Save Maintenance</button></div>`);$('crmClose').onclick=$('crmCancel').onclick=closeModal;$('mfLast').onchange=()=>{if($('mfLast').value)$('mfNext').value=dateAddMonths($('mfLast').value,$('mfInterval').value)};$('mfInterval').onchange=()=>{if($('mfLast').value)$('mfNext').value=dateAddMonths($('mfLast').value,$('mfInterval').value)};$('crmSaveMaint').onclick=()=>{Object.assign(m,{lastDate:$('mfLast').value,lastMileage:Number($('mfMileage').value||0),intervalMonths:Number($('mfInterval').value||0),nextDueDate:$('mfNext').value,nextDueMileage:Number($('mfNextMileage').value||0)});if(m.lastDate)v.lifeStory.push({date:m.lastDate,title:m.name+' completed',detail:`Recorded at ${Number(m.lastMileage||0).toLocaleString('en-GB')} miles`});save();closeModal();render()}}
function openCommunicationModal(c){modal(`<div class="crm-modal-head"><h2>Add Customer Contact</h2><button id="crmClose">×</button></div><div class="crm-field-grid"><label>Method<select id="coMethod"><option>Phone</option><option>Mobile</option><option>Email</option><option>SMS</option><option>WhatsApp</option><option>Letter</option><option>In person</option></select></label><label>Outcome<select id="coOutcome"><option>Spoke to customer</option><option>Message left</option><option>Booked</option><option>Declined</option><option>Awaiting response</option></select></label><label class="wide">Notes<textarea id="coNote"></textarea></label></div><div class="crm-form-actions"><button class="secondary" id="crmCancel">Cancel</button><button class="primary" id="crmSaveComm">Save Contact</button></div>`);$('crmClose').onclick=$('crmCancel').onclick=closeModal;$('crmSaveComm').onclick=()=>{c.communications=c.communications||[];c.communications.push({id:id('COM'),date:new Date().toISOString(),method:$('coMethod').value,outcome:$('coOutcome').value,note:$('coNote').value});save();closeModal();render()}}
function openDocumentModal(c){modal(`<div class="crm-modal-head"><h2>Add Document Reference</h2><button id="crmClose">×</button></div><div class="crm-field-grid"><label>Type<select id="doType"><option>Invoice</option><option>Estimate</option><option>VHC</option><option>Warranty</option><option>Photo</option><option>Service record</option><option>Correspondence</option></select></label>${field('Document name / reference','doName','') }<label class="wide">Notes<textarea id="doNote"></textarea></label></div><div class="crm-form-actions"><button class="secondary" id="crmCancel">Cancel</button><button class="primary" id="crmSaveDoc">Save Reference</button></div>`);$('crmClose').onclick=$('crmCancel').onclick=closeModal;$('crmSaveDoc').onclick=()=>{c.documents=c.documents||[];c.documents.push({id:id('DOC'),date:new Date().toISOString(),type:$('doType').value,name:$('doName').value,note:$('doNote').value});save();closeModal();render()}}
function showSummary(c){let due=(c.vehicles||[]).flatMap(v=>(v.maintenance||[]).filter(m=>maintStatus(m)!=='green').map(m=>`${displayReg(v.registration)}: ${m.name} ${m.nextDueDate?'due '+new Date(m.nextDueDate).toLocaleDateString('en-GB'):'date required'}`));modal(`<div class="crm-modal-head"><h2>Customer Summary</h2><button id="crmClose">×</button></div><div class="crm-note"><strong>${esc(customerName(c))}</strong> has been a customer since ${c.customerSince?new Date(c.customerSince).toLocaleDateString('en-GB'):'an unknown date'}. They have ${(c.vehicles||[]).length} linked vehicle(s), a Customer Health Score of ${customerHealth(c)}%, ${loyalty(c)} loyalty status and recorded lifetime spend of £${Number(c.lifetimeSpend||0).toLocaleString('en-GB')}. Preferred contact is ${esc(c.preferredContact||'not set')} ${c.preferredTime?'in the '+esc(c.preferredTime.toLowerCase()):''}.</div><h3>Next conversation</h3>${due.slice(0,8).map(x=>`<div class="crm-alert">${esc(x)}</div>`).join('')||'<p>No maintenance alerts.</p>'}${c.notes?`<h3>Important notes</h3><p>${esc(c.notes)}</p>`:''}`);$('crmClose').onclick=closeModal}
function dataIntegrity(){let issues=[];db.customers.forEach(c=>{if(!c.mobile&&!c.home&&!c.work)issues.push([c.id,'Missing telephone number']);if(!c.email)issues.push([c.id,'Missing email address']);if(!c.postcode)issues.push([c.id,'Missing postcode']);if(!(c.vehicles||[]).length)issues.push([c.id,'No vehicle linked']);(c.vehicles||[]).forEach(v=>{if(!v.vin)issues.push([displayReg(v.registration),'Missing VIN']);(v.maintenance||[]).forEach(m=>{if(!m.nextDueDate)issues.push([displayReg(v.registration),`${m.name}: next due date missing`])})})});let regs={};db.customers.forEach(c=>(c.vehicles||[]).forEach(v=>{let r=normReg(v.registration);regs[r]=(regs[r]||[]).concat(customerName(c))}));Object.entries(regs).filter(x=>x[1].length>1).forEach(([r,n])=>issues.push([displayReg(r),'Duplicate registration linked to '+n.join(', ')]));let names={};db.customers.forEach(c=>{let n=(customerName(c)+'|'+(c.postcode||'')).toLowerCase();names[n]=(names[n]||[]).concat(c.id)});Object.entries(names).filter(x=>x[1].length>1).forEach(([n,ids])=>issues.push([ids.join(', '),'Possible duplicate customers']));modal(`<div class="crm-modal-head"><h2>CRM Data Integrity Centre</h2><button id="crmClose">×</button></div><p class="muted">Finds incomplete or potentially duplicated records without changing workshop data.</p><div class="stats"><div class="stat-card"><strong>${issues.length}</strong><span>Issues found</span></div><div class="stat-card"><strong>${db.customers.length}</strong><span>Customers checked</span></div></div>${issues.map(x=>`<div class="crm-integrity-item"><strong>${esc(x[0])}</strong><span>${esc(x[1])}</span></div>`).join('')||'<div class="crm-note">No data integrity issues found.</div>'}`);$('crmClose').onclick=closeModal}

function findVehicleByRegistration(reg){let clean=normReg(reg);for(const c of db.customers){for(const v of (c.vehicles||[])){if(normReg(v.registration)===clean)return {customer:c,vehicle:v}}}return null}
function contactNumber(c){return c.mobile||c.home||c.work||''}
function loadNewJob(customerId,vehicleId){
 const c=db.customers.find(x=>x.id===customerId),v=c&&(c.vehicles||[]).find(x=>x.id===vehicleId);if(!c||!v)return;
 if(typeof window.show==='function')window.show('managerScreen');
 const set=(id,value)=>{const e=document.getElementById(id);if(e)e.value=value??''};
 set('reg',displayReg(v.registration));set('customer',customerName(c));set('phone',contactNumber(c));set('make',v.make);set('model',[v.model,v.variant].filter(Boolean).join(' '));set('mileage',v.mileage||'');
 let details=[];if(c.preferredContact)details.push(`Preferred contact: ${c.preferredContact}${c.preferredTime?' ('+c.preferredTime+')':''}`);if((c.preferences||[]).length)details.push('Preferences: '+c.preferences.join(', '));if(c.notes)details.push('Customer note: '+c.notes);details.push(`CRM: ${c.id} · ${loyalty(c)} customer · Health ${customerHealth(c)}%`);
 set('specialInstructions',details.join('\n'));
 window.__wai096LoadedCRM={customerId:c.id,vehicleId:v.id,customerLoyalty:loyalty(c),customerHealth:customerHealth(c),preferredContact:c.preferredContact||'',email:c.email||'',address:[c.address1,c.town,c.county,c.postcode].filter(Boolean).join(', ')};
 document.getElementById('reg')?.dispatchEvent(new Event('input',{bubbles:true}));
 document.getElementById('managerScreen')?.scrollIntoView({behavior:'smooth',block:'start'});
}
function openMaintenance(customerId,vehicleId){selectedId=customerId;activeTab='maintenance';if(typeof window.show==='function')window.show('crmScreen');render();setTimeout(()=>{document.querySelector(`[data-maint^="${vehicleId}|"]`)?.scrollIntoView({behavior:'smooth',block:'center'})},50)}
window.WorkshopCRMBridge={findVehicleByRegistration,loadNewJob,openMaintenance,getLoaded:()=>window.__wai096LoadedCRM||null,clearLoaded:()=>{window.__wai096LoadedCRM=null}};
function init(){if(!$('crmScreen'))return;$('crmNewCustomerBtn').onclick=()=>openCustomerModal();$('crmDataIntegrityBtn').onclick=dataIntegrity;$('crmRefresh').onclick=render;$('crmSearch').oninput=renderList;$('crmFilter').onchange=renderList;render();window.renderWAI096CRM=render}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
